## Create a random tensor with shape (7, 7)


In [2]:
import torch

# Creating a random tensor
X = torch.rand(size=(7, 7))
X, X.shape

(tensor([[0.8943, 0.6062, 0.5448, 0.9974, 0.9650, 0.7691, 0.9843],
         [0.1935, 0.6231, 0.3852, 0.2812, 0.7335, 0.7972, 0.2619],
         [0.4957, 0.9596, 0.8601, 0.4562, 0.8436, 0.1399, 0.6593],
         [0.4583, 0.9578, 0.6427, 0.6763, 0.4525, 0.1616, 0.5858],
         [0.5210, 0.7186, 0.9915, 0.5746, 0.9047, 0.7702, 0.2856],
         [0.2244, 0.8201, 0.7543, 0.7651, 0.1632, 0.6899, 0.2042],
         [0.0364, 0.5908, 0.0693, 0.2032, 0.9875, 0.0699, 0.7389]]),
 torch.Size([7, 7]))

### Perform a matric multiplication on the tensor above with another random tensor with shape `(1, 7)` (hint: may have to do transpose of the second tensor)

In [3]:
# Creating another tensor
Y = torch.rand(size=(1, 7))

# Z = torch.matmul((X, Y))  # Error as the shape matter
Z = torch.matmul(X, Y.T)

Z, Z.shape

(tensor([[2.5680],
         [1.4197],
         [2.1497],
         [1.8369],
         [2.1557],
         [1.4459],
         [1.3277]]),
 torch.Size([7, 1]))

### Set the random seed to `0` and do 2 and 3 again .

The output should be:

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))


In [4]:
# Set the manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# matrix multiply tensors
Z = torch.matmul(X, Y.T)

Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

* If there is , set the GPU random seed to `1234`



In [5]:
# Set random seed on the GPU

torch.cuda.manual_seed(1234)

### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need to access to a GPU ) . Set `torch.manual_seed(1234)` when creating the tensor (this doesn't have to be the GPU random seed) . The output should be something like this.

Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))



In [6]:
# Set random seed

torch.manual_seed(1234)

# Check for access to GPU

device = "cuda" if torch.cuda.is_available() else "CPU"

print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2, 3)).to(device)
tensor_B = torch.rand(size=(2, 3)).to(device)

tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

### 7. Perform a matrix multiplication on the tensors you made above ( adjust the shape of the tensor if needed)

The output should look like:

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))




In [9]:
tensor_C = torch.matmul(tensor_A, tensor_B.T)

tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### Find the maximum and minimum values of  the output of 7

In [10]:
# Find max
max = torch.max(tensor_C)

# Find min

min = torch.min(tensor_C)

max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### Find maximum and minimum indec values of the output of 7.


In [11]:
# Find the arg max

arg_max = torch.argmax(tensor_C)


# Find argmin
arg_min = torch.argmin(tensor_C)

arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

###10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimension removed to be left with a tensor of shape `(10)`, Set the seed to `7` when you create it and print the first tensor and it's shape as well as the second tensor and it's shape .


he output should look like:

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])



In [12]:
torch.manual_seed(7)

rand_tensor = torch.rand(size=(1, 1, 1, 10))

# Remove all single dimensions
no_single_dim_tensor = rand_tensor.squeeze()

# /print out tensors
print(rand_tensor, rand_tensor.shape)
print(no_single_dim_tensor,no_single_dim_tensor.shape )

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
