#Adaptie MaxPool2D

class torch.nn.AdaptiveMaxPool2d(output_size, return_indices=False)

Applies a 2D adaptive max pooling over an input signal composed of several input planes.
The output is of size Hout x Wout for any input size. The no: of output features is equal to nu: of input planes.


In [2]:
import torch.nn as nn
import torch

In [3]:
# Example
# Traget output size of 5 x 7 '
m = nn.AdaptiveMaxPool2d((5, 7))

input = torch.randn(1, 64, 8, 9)
output = m(input)

# Target output size of 7x 8x (square)
m = nn.AdaptiveMaxPool2d((None, 7))
input = torch.randn(1, 64, 10, 9)
output = m(input)

## Reflection Pad 1d


In [4]:
m = nn.ReflectionPad1d(2)
input = torch.arange(8, dtype=torch.float).reshape(1, 2, 4)

input

tensor([[[0., 1., 2., 3.],
         [4., 5., 6., 7.]]])

In [5]:
m(input)

tensor([[[2., 1., 0., 1., 2., 3., 2., 1.],
         [6., 5., 4., 5., 6., 7., 6., 5.]]])

In [6]:
# Using different padding for differnet sides
m = nn.ReflectionPad1d((3, 1))
m(input)

tensor([[[3., 2., 1., 0., 1., 2., 3., 2.],
         [7., 6., 5., 4., 5., 6., 7., 6.]]])

## Zeropad 1d
class torch.nn.Zeropad1d(padding)
Pads the input tensor boundaries with zero.

For N-dimensional padding, use `torch.nn.functional.pad()`.

In [7]:
m = nn.ZeroPad1d(2)

input = torch.randn(1, 2, 4)
# This line makes a tensor with 3d: **1, sampling, 2, elements, each having 4 features**

input

tensor([[[ 1.6763, -0.9041,  0.5412,  0.8422],
         [-0.7987, -0.3988,  1.2214, -0.6114]]])

In [8]:
m(input)

tensor([[[ 0.0000,  0.0000,  1.6763, -0.9041,  0.5412,  0.8422,  0.0000,
           0.0000],
         [ 0.0000,  0.0000, -0.7987, -0.3988,  1.2214, -0.6114,  0.0000,
           0.0000]]])

In [9]:
# Using different padding for different sides
m = nn.ZeroPad1d((3, 1))
m(input)

tensor([[[ 0.0000,  0.0000,  0.0000,  1.6763, -0.9041,  0.5412,  0.8422,
           0.0000],
         [ 0.0000,  0.0000,  0.0000, -0.7987, -0.3988,  1.2214, -0.6114,
           0.0000]]])

## nn.ConstantPad2d
Pad input tensor boundaries with a constant value.
class torch.nn.constantPad2d(padding, value)

Pads the input tensor boudaries with a constant value.

for N-D padding Use `torch.nn.functional.pad()`

padding (int, tuple) – the size of the padding. If is int, uses the same padding in all boundaries. If a 4-tuple, uses (padding_lef, tpadding_right, padding_top, padding_botto,)


In [14]:
m = nn.ConstantPad2d(2, 3.5)
input = torch.randn(1, 2, 2)
input



tensor([[[ 0.3117,  0.4913],
         [-2.8321,  0.6346]]])

In [15]:
m(input)


tensor([[[ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
         [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
         [ 3.5000,  3.5000,  0.3117,  0.4913,  3.5000,  3.5000],
         [ 3.5000,  3.5000, -2.8321,  0.6346,  3.5000,  3.5000],
         [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
         [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000]]])

In [16]:
# Using different padding for different sides.
m = nn.ConstantPad2d((3, 0, 2, 1), 3.5)
m(input)

tensor([[[ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
         [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
         [ 3.5000,  3.5000,  3.5000,  0.3117,  0.4913],
         [ 3.5000,  3.5000,  3.5000, -2.8321,  0.6346],
         [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000]]])

##Circularpad1d
class torch.nn.CircularOad1d(padding)
Pads the input tensor using the padding of the input boundaries

Tensor values at the beginning of the dimension are used to pad the end, and values at the end are used to pad the beginning. If negative padding is applied then the ends of the tensor get removed.


In [17]:
m = nn.CircularPad1d(2)
input = torch.arange(8, dtype=torch.float).reshape(1, 2, 4)
input

tensor([[[0., 1., 2., 3.],
         [4., 5., 6., 7.]]])

In [18]:
m(input)

tensor([[[2., 3., 0., 1., 2., 3., 0., 1.],
         [6., 7., 4., 5., 6., 7., 4., 5.]]])

In [19]:
# Using different paddings for different sides
m = nn.CircularPad1d((3, 1))
m(input)

tensor([[[1., 2., 3., 0., 1., 2., 3., 0.],
         [5., 6., 7., 4., 5., 6., 7., 4.]]])

# Non linear activations (weighted sum, nonlinearity)

## ELU
class torch.nn.ELU(alpha=1.0, inplace=False)



In [20]:
# Example
m = nn.ELU()
input = torch.randn(2)
output = m(input)

## HardShrink
Apply hardshrinkage function element wise.
class torch.nn.HardShrink(lambd=0.5)

In [22]:
m = nn.Hardshrink()
input = torch.randn(2)
output  = m(input)

## Hardsigmoid
Apply the Hardsigmoid function element wise



In [23]:
# Example
m = nn.Hardsigmoid()
input = torch.randn(2)
output = m(input)

## Hardtanh
 class torch.nn.Hardtanh(min_value=-1.0. max_val=1.0, inplace=False)

Applies the HardTanh fun: element-wise



In [24]:
m = nn.Hardtanh(-2, 2)
input = torch.randn(2)
output = m(input)

## LeakyRELU

Class torch.nn.LeakyReLU(negative_slope=0.01, inplace=False)


Applies the LeakyReLU function element-wise


In [25]:
# Examples
m = nn.LeakyReLU(0.1)
input = torch.randn(2)
output = m(input)

## SELU
Scaled ELU. Applies SELU function element-wise

SELU(x) = scale * (max(0, x) + min(0, alpha*(exp(x)-1)))

with alpha = 1.6732632423543772848170429916717
and scale=1.0507009873554804934193349852946scale=1.0507009873554804934193349852946.


In [26]:
# Example
m = nn.SELU()
input = torch.randn(2)
output = m(input)

## GELU ( Gaussian Error Linear Unit function).

class torch.nn.GELU(approximate='none')

Applies the Gaussian Error Linear Units function.

GELU(x) = x * phi(x)

Where phi(x) is the Cumulative Distribution  Function for Gaussian DIstribution.

When approximate argument is 'tanh'  Gelu is estimated as
GELU(x) = 0.5 * x * (1 + Tanh(sqrt(2/pi) * (z _ 0.044715* x ^3)))



In [27]:
m= nn.GELU()
input = torch.randn(2)
output = m(input)

## Sigmoid

* Applies sigmiod elementwise

In [28]:
m = nn.Sigmoid()
input = torch.randn(2)
output = m(input)

## GLU
Gated Linear Unit.

class torch.nn.GELU(dim=-1)

Applies the gated linear unit fun:
GLU(a, b) = a # sig(b)
where the a is first half on input and b ins second half of the matix.


In [29]:
m = nn.GELU()
input = torch.randn(4, 2)
output = m(input)