In [7]:
import torch

scalar =  torch.tensor(7)
scalar


tensor(7)

In [8]:
scalar.ndim


0

In [9]:
scalar.item()

7

In [10]:
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [11]:
vector.shape

torch.Size([2])

In [12]:
# matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

The matrix and tensors are denoted by capital letters such as X, W; while the vars are lowercase.


In [18]:
# creating a random tensor with size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.4745, 0.9947, 0.6485, 0.1750],
         [0.1881, 0.7829, 0.6451, 0.1327],
         [0.6387, 0.8573, 0.6697, 0.4039]]),
 torch.float32)

In [19]:
# Creating a random tensor of size (224, 224, 3)

random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [20]:
# creatin a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype


(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [21]:
# creating a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [22]:
# Use torch.arange() , torch.range() is deprecated
zero_to_deprecated = torch.range(0, 10)

zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

/tmp/ipython-input-755390065.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_deprecated = torch.range(0, 10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])



The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).


In [24]:
# Precision : Amount of detail used to describe a number.

# The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

# This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.


In [25]:
# Default datatypes for tensor is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # Defaults to None, which is torch.float
                               device=None, # Defaults to None which uses default tensor type
                               requires_grad=False) # If True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device




(torch.Size([3]), torch.float32, device(type='cpu'))

In [26]:
# creating a tensor with dtype=torch.float16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)

float_16_tensor.dtype

torch.float16

In [27]:
torch.float16


torch.float16

In [28]:
# Creating a random tensor

some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")  # will default to CPU


tensor([[0.4898, 0.1710, 0.1705, 0.2246],
        [0.8275, 0.3296, 0.6147, 0.3912],
        [0.2917, 0.2205, 0.1124, 0.1715]])
shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.



**Manipulating Tensors**
In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.





*Basic Operations*


In [29]:
# Create a tensor of values abd add a number to it
tensor = torch.tensor([1, 2, 3])

tensor  + 10


tensor([11, 12, 13])

In [30]:
# Multiply it by 10
tensor * 10


tensor([10, 20, 30])

In [31]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [32]:
# Adding and reassiging tensor
tensor = tensor + 10
tensor


tensor([1, 2, 3])

In [33]:
torch.multiply(tensor, 10 )


tensor([10, 20, 30])

In [34]:
# Elementwise multiplication (each element multiplies its equivalent , index 0->0,  1->1, 2->2)
print(tensor, "*", tensor  )
print("Equals:", tensor * tensor )

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [35]:
import torch
tensor = torch.tensor([1, 2, 3])

tensor.shape


torch.Size([3])

In [36]:
torch.matmul(tensor, tensor)


tensor(14)

In [37]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [38]:
# Doing matrix multiplication by hand
%%time

value  = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.19 ms, sys: 0 ns, total: 1.19 ms
Wall time: 2.76 ms


tensor(14)

In [39]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 430 µs, sys: 50 µs, total: 480 µs
Wall time: 454 µs


tensor(14)

In [40]:
# Shapes need to be in right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)


tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# To perform matrix multiplication, the inner dimensions must match.
# Shape of tensor_A: (3, 2)
# Shape of tensor_B: (3, 2)
# Inner dimensions are 2 and 3, which do not match.

# We need to transpose tensor_B to make the shapes compatible.
# The transpose of a (3, 2) tensor is a (2, 3) tensor.
# After transposing tensor_B, the shapes will be (3, 2) and (2, 3).
# The inner dimensions are now 2 and 2, which match.
print(f"Shape of tensor_A: {tensor_A.shape}")
print(f"Shape of tensor_B: {tensor_B.shape}")

tensor_B_T = tensor_B.T # or tensor_B.transpose(0, 1)
print(f"Shape of tensor_B_T: {tensor_B_T.shape}")

torch.matmul(tensor_A, tensor_B_T)

Shape of tensor_A: torch.Size([3, 2])
Shape of tensor_B: torch.Size([3, 2])
Shape of tensor_B_T: torch.Size([2, 3])


tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [41]:
# To correctly do the math we need to take the transpose of the matrix
print(tensor_A)
print(tensor_B.T)


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [42]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} ( same as above ), tensor_B.T = {tensor_B.shape}\n")

print(f"Multiplying: {tensor_A.shape} * {tensor_B.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"Output shape: { output.shape }")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) ( same as above ), tensor_B.T = torch.Size([3, 2])

Multiplying: torch.Size([3, 2]) * torch.Size([3, 2]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
Output shape: torch.Size([3, 3])


In [43]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [44]:
# Since linear layer starts with a random weights matrix, let's make it reproducible

torch.manual_seed(42)
# this uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value


x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output :\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output :
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [45]:
class LSTMCell(Module):
  def __init__(self, ni, nh):
    self.forget_gate = nn.Linear(ni + nh , nh)
    self.input_gate = nn.Linear(ni + nh, nh)
    self.cell_gate = nn.Linear(ni + nh, nh)
    self.output_gate = nn.Linear(ni + nh, nh)

  def forward(self, input, state):
    h,c = state
    h =  torch.stack([h, input] dim=1)
    forget = torch.sigma(self, forget_gate(h))
    c = c * forget
    i = torch.sigmoid(self.input_gate)
    cell = torch.tanh(self.cell_gate(h))
    c = c +  inp * cell
    out = torch.sigmoid(self.cell_gate(h))
    h = torch.tanh(self.output_gate(torch.cat([h, c], dim=1)))
    return h, (h, c)



SyntaxError: invalid syntax. Perhaps you forgot a comma? (ipython-input-3935553637.py, line 10)

In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

In [46]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [47]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [48]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [49]:
# Creating a int_8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [50]:
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [51]:
# Adding extra dimension to the tensor
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [52]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [53]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [54]:
# Stack the tensors om top each other
x_stacked = torch.stack([x ] * 10, dim=0)  # try changing the dim to dim=1
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [55]:
print(f"Previous tensor: {x_reshaped}")
print(f" Previous shape: {x_reshaped.shape}")

# Remove extra dims: from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor:{x_reshaped}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
 Previous shape: torch.Size([1, 7])

New tensor:tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([7])


In [56]:
# torch.unsqueeze add dimension value of 1 to the specific index
print(f"Previuos tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed.shape}")


Previuos tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: torch.Size([1, 7])


In [57]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [58]:
# Indexing (selecting data from tensors)
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [59]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")


First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [60]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [61]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [62]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [63]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [64]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [65]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [66]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [67]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor


(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [68]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [69]:
import torch
import random

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# have to reset the seed every time a new rand() is  called
# Without this, tensor_D would be different to tensot_C

torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f" Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D


 Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [70]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [71]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [72]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [73]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [74]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

array([1, 2, 3])

In [75]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [76]:
tensor_on_gpu

tensor([1, 2, 3])

In [77]:
# Random tesnor of shape (7, 7)
import torch

random_tensor = torch.rand(7, 7)
print(random_tensor)

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])


In [5]:
import torch

random_tensor_one = torch.rand(7, 7)
random_torch_two = torch.rand(1, 7)

random_2_transpose = random_torch_two.T
print(random_2_transpose)


tensor([[0.4220],
        [0.6399],
        [0.2939],
        [0.2767],
        [0.1819],
        [0.5101],
        [0.1898]])


In [6]:
# Make a random tensor of shape (7, 7)

import torch

X = torch.rand(size=(7, 7))
X, X.shape


(tensor([[0.7391, 0.0192, 0.5735, 0.8833, 0.4904, 0.1955, 0.3295],
         [0.7446, 0.4269, 0.6135, 0.4304, 0.2043, 0.6622, 0.1858],
         [0.7985, 0.5192, 0.4128, 0.7264, 0.6409, 0.0499, 0.4313],
         [0.3287, 0.4557, 0.1590, 0.9239, 0.1556, 0.3732, 0.9567],
         [0.0325, 0.6228, 0.5289, 0.5779, 0.6163, 0.5002, 0.1716],
         [0.9001, 0.6665, 0.0061, 0.6979, 0.9762, 0.8289, 0.5825],
         [0.5045, 0.3091, 0.5754, 0.5059, 0.4548, 0.3752, 0.9816]]),
 torch.Size([7, 7]))

In [81]:
# Performing matrix multiplication with another random tensor (1, 7)

X =  torch.rand(size=(7, 7))

Y = torch.rand(size=(1, 7))

Z = torch.matmul(X, Y.T)

Z, Z.shape

(tensor([[1.2748],
         [1.1652],
         [1.0182],
         [1.7959],
         [1.6076],
         [1.8623],
         [0.7118]]),
 torch.Size([7, 1]))

In [ ]:
# Set randomseed on the GPU
torch.cuda.manual_seed(1234)

Create 2 random tensors of shape (2, 3)  and send them both to the GPU . Set torch.manual_seed(1234) when creating the tensors.

In [82]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda:" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")


# Create 2 random tensors on GPU

tensor_A = torch.rand(size=(2, 3)).to(device)
tensor_B = torch.rand(size=(2, 3)).to(device)

tensor_A, tensor_B

Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [83]:
# Performing matmul on the tensors above:
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

In [84]:
# Find the maximum value of the output in the above
max = torch.max(tensor_C)

# Find the minimum
min = torch.min(tensor_C)

max, min

(tensor(0.5617), tensor(0.3647))

In [85]:
# Find the max and min index value of out: 7
arg_max =  torch.argmax(tensor_C)

# Find the min
arg_min =  torch.argmin(tensor_C)
arg_max, arg_min

(tensor(3), tensor(0))

Make a tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dims  removed to be left with tensor of shape (10). Set the seed to 7 when you create it and print out shape of first tensor and it's shape as well as second tensor  and it's shape .


In [86]:
# Set seed
torch.manual_seed(7)

# Create a random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove the single dims:
tensor_E = tensor_D.squeeze()

# Print out tensors

print(tensor_D, tensor_D.shape)

print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
