# Sparse Layers

## Embedding

** class torch.nn.Embedding(num_embeddings, embedding_dim, padding_idx=None, max_norm=None, norm_type=2.0, scale_grad_by_freq=False, sparse=False, _weight=None, _freeze=False, device=None, dtype=None)**

A simple lookup table that stores embeddings of a fixed dict: and size

This module is often used to store word embeddings and retrieve them using indices. The input to the module is a list of indices, and the output is the corresponding word embeddings.



### Parameters:

* num_embeddings (int) - size of dictionary of embeddings
* enbedding_dim (int): the size of each embedding vector
* padding_idx(int, optional) - If specified the entires at `padding_idx` don't contribute to the gradient; therefore the embedding vector at `padding_idx` is not updated during training , ie it remains as a fixed "pad",. For a newly constructed Embedding the embedding vector at the `padding_idx` will default to all zeros , but can be updated to another value to be used as the padding vector.
* max_norm (float, optional) – If given, each embedding vector with norm larger than max_norm is renormalized to have norm max_norm.
* norm_type (float, optional) – The p of the p-norm to compute for the max_norm option. Default 2.
* scale_grad_by_freq (bool, optional) – If given, this will scale gradients by the inverse of frequency of the words in the mini-batch. Default False.
* sparse (bool, optional) – If True, gradient w.r.t. weight matrix will be a sparse tensor.

### Variables
**weight (Tensor) ** The learnable weights of the moudle of shape (num_embeddings, embedding_dim) initialised from N(0, 1)


#### Shape
* Input (*) int Tensor or LongTensor of arbitrary shape containing the indices to extract
* Output: (∗,H), where * is the input shape and H=embedding_dimH=embedding_dim

# Examples


In [18]:
import torch
import torch.nn as nn

In [19]:
# an Embeddings module containing 10 tensors of size 3
embedding = nn.Embedding(10, 3)
# A batch of 2 samples of 4 indices each
input = torch.LongTensor([[1, 2, 4, 5], [4, 3, 2, 9]])
embedding(input)

tensor([[[ 0.8780, -0.7794,  0.4825],
         [-1.9544,  0.5240,  0.3929],
         [-1.0189, -0.4491, -0.9503],
         [ 0.5924, -0.7245,  2.0956]],

        [[-1.0189, -0.4491, -0.9503],
         [ 0.0100,  1.6775,  0.6254],
         [-1.9544,  0.5240,  0.3929],
         [ 0.2928,  2.3553, -1.6863]]], grad_fn=<EmbeddingBackward0>)

In [20]:
# example with padding_idx
padding_idx = 0
embedding = nn.Embedding(3, 3, padding_idx=padding_idx)
embedding.weight

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000],
        [-1.0706,  0.3401,  1.6228],
        [ 1.7570,  1.1235, -1.8219]], requires_grad=True)

In [21]:
with torch.no_grad():
  embedding.weight[padding_idx] = torch.ones(3)
embedding.weight

Parameter containing:
tensor([[ 1.0000,  1.0000,  1.0000],
        [-1.0706,  0.3401,  1.6228],
        [ 1.7570,  1.1235, -1.8219]], requires_grad=True)

## Parameters
* embeddings (Tensor) - FloatTensor containing weights for the Embedding. First dim: is being padded to the Embedding as `num_embeddings`, second as `embedding_dim`

* freeze( bool, optional) - If `True` , the tensor doesn't get updated in the learning process.
Equivalent to `embedding.weight.requires_grad=False` . Default: `True`

* padding_idx (int, optional) - If specified , the entires at `padding_idx` do not contributes to the gradient, therefore the embedding vector at `padding_idx` is not updated during training, .i.e it remains as a fixed "pad"

* max_norm (float, optional)

* norm_type (float, optional)
* scale_grad_by_freq(bool, optional)
* sparse (bool, optional)


### Examples

In [22]:
# FloatTensor containing pretrained weights
weight = torch.FloatTensor([[1, 2.3, 3], [4, 5.1, 6.3]])

embedding = nn.Embedding.from_pretrained(weight)
input = torch.LongTensor([1])

embedding(input)

tensor([[4.0000, 5.1000, 6.3000]])

# EmbeddingBag
 **class torch.nn.EmbeddingBag(num_embeddings, embedding_dim, max_norm=None, norm_type=2.0, scale_grad_by_freq=False, mode='mean', sparse=False, _weight=None, include_last_offset=False, padding_idx=None, device=None, dtype=None)**


Compute sums or means of ‘bags’ of embeddings, without instantiating the intermediate embeddings.

EmbeddingBag also supports per-sample weights as an argument to the forward pass. This scales the output of the Embedding before performing a weighted reduction as specified by `mode`. If `per_sample_weights` is passed, the only supported `mode` is `"sum"`, which computes a weighted sum according to `per_sample_weights.`


## Examples

In [23]:
import torch
import torch.nn as nn


In [24]:
# an EmbeddingBag module containig 10 tensors of size 3
embedding_sum = nn.EmbeddingBag(10, 3, mode="sum")
# a batch of 2 samples of 4 indices each
input = torch.tensor([1, 2, 4, 5, 4, 3, 2, 9], dtype=torch.long)
offsets = torch.tensor([0, 4], dtype=torch.long)
embedding_sum(input, offsets)

tensor([[ 1.8239, -2.6671, -3.9802],
        [ 1.7420, -1.5966, -0.9367]], grad_fn=<EmbeddingBagBackward0>)

 ### forward(input, offsets=None, per_sample_weights=None)
## Parameters:
* input (tensor) - Tensor containig bags of indices into the embedding matric.
* offsets (Tensor, optional) - Only used when `input` is 1D. `offsets` determines the starting index position of each bag in `input`.
* per_sample_weights (Tensor, optional) - a tensor of float/double weights , or None to indicate all weights should be taken to be `1` . IF specified `per_sample_weights` must have exactly the same as input and is treated as having the same `offsets` if those are not `None`.

### Returns
Tensor output shape of (B, embedding_dim)

### Return Type:
Tensor

#### classmethod from_pretrained(embeddings, freeze=True, max_norm=None, norm_type=2.0, scale_grad_by_freq=False, mode='mean', sparse=False, include_last_offset=False, padding_idx=None)*italicized text*

create EmbeddingBag instance from given 2-d FloatTensor.

* embeddings (Tensor) – FloatTensor containing weights for the EmbeddingBag. First dimension is being passed to EmbeddingBag as ‘num_embeddings’, second as ‘embedding_dim’.
* freeze (bool, optional) – If True, the tensor does not get updated in the learning process. Equivalent to embeddingbag.weight.requires_grad = False. Default: True
* max_norm (float, optional) – See module initialization documentation. Default: None
* norm_type (float, optional) – . Default 2.
* scale_grad_by_freq (bool, optional) –Default False.
* mode (str, optional) Default "mean"
* sparse (bool, optional) - Defualt "False"
* include_last_offset (bool, optional) - Default False
* Paddding_idx(int, optional) - Default `None`


##### Return Type
** EmbeddingBag **

**Examples **


In [ ]:
# FloatTensor containing pretrained weights
weight = torch.FloatTensor([[1, 2.3, 3], [4, 5.1, 6.3]])
embeddingbag = nn.EmbeddingBag.from_pretrained(weight)
# Get embeddings for index 1
input = torch.LongTensor([[1, 0]])
embeddingbag(input)