Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing.



In [3]:
import torch
import numpy as np


## Tensor Initialization
Tensors can be initialized in various ways. Here is an example.
**Directly from data**
 Tensors can be created directly from the data. The data type is automatically inferred.



In [4]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

**From a Numpy array**
Tensors can be created from NumPy arrays (and vice versa)





In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**From another tensor**
The new tensor retains the properties (shape, and datatype) of the augmented tensor , unless explicitly overridsen

In [6]:
x_ones = torch.ones_like(x_data) # retain the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor :\n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor :
 tensor([[0.9379, 0.0019],
        [0.1326, 0.8239]]) 



**With random or constact values**

`shape` is a tuple of tenor dimesion. In the functio below , it determines the dimensinality of the output tensor.


In [7]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")


Random Tensor: 
 tensor([[0.6924, 0.8419, 0.6201],
        [0.7142, 0.4724, 0.4114]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## Tensor attributes
Tensor attributes describes their shape, datatypes, and the device on which they are stored.


In [8]:
tensor = torch.rand(3, 4)

print(f"Shpae of tensor: {tensor.shape}")
print(f"Datatypes of tensor : {tensor.dtype}")
print(f"Device tensor is stoerd is : {tensor.device}")

Shpae of tensor: torch.Size([3, 4])
Datatypes of tensor : torch.float32
Device tensor is stoerd is : cpu


## Tensor operations
Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, and more
Each of them can be run on the GPU


In [9]:
import torch
import numpy as np

# We move the tensor to the FPU if available
if torch.cuda.is_available():
  tensor = tensor.to("cuda")
  print(f"Device tensor is stored on : {tensor.device}")

Device tensor is stored on : cuda:0


**Strandard numpy like indexing and slicing**


In [14]:
tensor = torch.ones(4, 4)
# This creates a 4×4 tensor filled with 1s:

tensor[:, 2] = 0
# : means all rows
# 2 means column index 1 (second column)
# = 0 sets that entire column to 0
# So it replaces the second column with zeros.
print(tensor)

tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])


Joining tensors You can use torch.cat to concatenate a sequence of tensors along a given dimension. See also torch.stack, another tensor joining op that is subtly different from torch.cat.



In [15]:
t1  = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.]])


**Multipling the tensors**


In [16]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]]) 

tensor * tensor 
 tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])


**This compute the matrix multipication of the 2 tensors**


In [18]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


**IN place operations that have a _ sufix are in-place . For eg: `x.copy_y()`, `x.t_()` will  change `x.`**



In [19]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]]) 

tensor([[6., 6., 5., 6.],
        [6., 6., 5., 6.],
        [6., 6., 5., 6.],
        [6., 6., 5., 6.]])


# Bridge with numpy
Tensors on the CPU and NumPy arrays share their underlying memory locations, and changing one will change the other.


In [21]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NunPy array


In [22]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


# NumPy array to Tensor

In [23]:
n= np.ones(5)
t = torch.from_numpy(n)

change in the NumPy array reflects in the tensor


In [26]:
np.add(n, 1, out=n)
print(f"t : {t}")
print(f"n: {n}")

t : tensor([4., 4., 4., 4., 4.], dtype=torch.float64)
n: [4. 4. 4. 4. 4.]
